// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

uniform int _VolumeSize;
Texture3D<float> _VolumeTexture;
RWStructuredBuffer<float> _VoxelBuffer;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint idx = id.x + id.y * _VolumeSize + id.z * _VolumeSize * _VolumeSize;
    _VoxelBuffer[idx] = _VolumeTexture[id];
}
